# Generated by Django 2.1.15 on 2020-01-06 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
