# Generated by Django 2.1.11 on 2020-07-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0002_message_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
