# Generated by Django 2.1.11 on 2020-09-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0004_message_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image',
            new_name='attached',
        ),
    ]
