# Generated by Django 2.1.11 on 2019-09-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('short_description', models.CharField(max_length=50, verbose_name='Short Description')),
                ('image', models.ImageField(upload_to='gallery/categorie/', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.Categorie', verbose_name='Categorie'),
        ),
    ]
