# Generated by Django 2.1.12 on 2019-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20190914_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='alias',
            field=models.CharField(default=1, max_length=20, verbose_name='Alias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Alias'),
        ),
    ]
