# Generated by Django 2.1.12 on 2019-09-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_auto_20190914_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
