# Generated by Django 2.1.12 on 2019-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20190914_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='badge',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='badge',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='short_description_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='short_description_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='short_description_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='status_de',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='status_en',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='status_es',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_de',
            field=models.TextField(blank=True, default='\n<strong>Ingrese su título aquí...</strong><br><br>\n\n<p> <b>Ingrese aquí su texto...</b></p>\n\n<!--more--><br><br>\n\n<p> <b>Ingrese más información aquí...</b></p>\n\n<!--more--><br><br>\n\n<strong>Quienes somos</strong><br><br>\n\n<p><b>Por favor ingrese aquí su texto...</b></p><br><br>\n\n<strong>Misión</strong><br><br>\n\n<p><b>Por favor ingrese aquí su texto...</b></p><br><br>\n\n<table class="table table-bordered tours-tabs__table" style="width: 100%px;">\n<tbody>\n<tr>\n <td style="width: 213px;"><strong>SALIDA / RETORNO</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la salida...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>HORA DE SALIDA</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la hora de salida...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>HORA DE LLEGADA</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la hora de llegada...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>NR. DE TOUR PARA RESERVAS</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí el nro de tour...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>TRASLADO DESDE </strong></td>\n <td style="width: 574.233px;"><strong><b>Ingrese aquí el traslado...</b></strong></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>INCLUIDO [icon_tick state="on"] </strong></td>\n <td style="width: 574.233px;">\n  <b>Ingrese aquí lo que va incluido en el paquete como una lista...</b>\n  <ul><li><b><br></b></li><li><b><br></b></li><li><b><br></b></li></ul>\n </td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>NO INCLUIDO [icon_tick state="off"] </strong></td>\n <td style="width: 574.233px;">\n  <b>Ingrese aquí lo que no va incluido en el paquete como una lista...</b>\n  <ul><li><b><br></b></li><li><b><br></b></li><li><b><br></b></li></ul>\n </td>\n</tr>\n</tbody>\n</table>\n', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_en',
            field=models.TextField(blank=True, default='\n<strong>Ingrese su título aquí...</strong><br><br>\n\n<p> <b>Ingrese aquí su texto...</b></p>\n\n<!--more--><br><br>\n\n<p> <b>Ingrese más información aquí...</b></p>\n\n<!--more--><br><br>\n\n<strong>Quienes somos</strong><br><br>\n\n<p><b>Por favor ingrese aquí su texto...</b></p><br><br>\n\n<strong>Misión</strong><br><br>\n\n<p><b>Por favor ingrese aquí su texto...</b></p><br><br>\n\n<table class="table table-bordered tours-tabs__table" style="width: 100%px;">\n<tbody>\n<tr>\n <td style="width: 213px;"><strong>SALIDA / RETORNO</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la salida...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>HORA DE SALIDA</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la hora de salida...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>HORA DE LLEGADA</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la hora de llegada...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>NR. DE TOUR PARA RESERVAS</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí el nro de tour...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>TRASLADO DESDE </strong></td>\n <td style="width: 574.233px;"><strong><b>Ingrese aquí el traslado...</b></strong></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>INCLUIDO [icon_tick state="on"] </strong></td>\n <td style="width: 574.233px;">\n  <b>Ingrese aquí lo que va incluido en el paquete como una lista...</b>\n  <ul><li><b><br></b></li><li><b><br></b></li><li><b><br></b></li></ul>\n </td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>NO INCLUIDO [icon_tick state="off"] </strong></td>\n <td style="width: 574.233px;">\n  <b>Ingrese aquí lo que no va incluido en el paquete como una lista...</b>\n  <ul><li><b><br></b></li><li><b><br></b></li><li><b><br></b></li></ul>\n </td>\n</tr>\n</tbody>\n</table>\n', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_es',
            field=models.TextField(blank=True, default='\n<strong>Ingrese su título aquí...</strong><br><br>\n\n<p> <b>Ingrese aquí su texto...</b></p>\n\n<!--more--><br><br>\n\n<p> <b>Ingrese más información aquí...</b></p>\n\n<!--more--><br><br>\n\n<strong>Quienes somos</strong><br><br>\n\n<p><b>Por favor ingrese aquí su texto...</b></p><br><br>\n\n<strong>Misión</strong><br><br>\n\n<p><b>Por favor ingrese aquí su texto...</b></p><br><br>\n\n<table class="table table-bordered tours-tabs__table" style="width: 100%px;">\n<tbody>\n<tr>\n <td style="width: 213px;"><strong>SALIDA / RETORNO</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la salida...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>HORA DE SALIDA</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la hora de salida...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>HORA DE LLEGADA</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí la hora de llegada...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>NR. DE TOUR PARA RESERVAS</strong></td>\n <td style="width: 574.233px;"><b>Ingrese aquí el nro de tour...</b></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>TRASLADO DESDE </strong></td>\n <td style="width: 574.233px;"><strong><b>Ingrese aquí el traslado...</b></strong></td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>INCLUIDO [icon_tick state="on"] </strong></td>\n <td style="width: 574.233px;">\n  <b>Ingrese aquí lo que va incluido en el paquete como una lista...</b>\n  <ul><li><b><br></b></li><li><b><br></b></li><li><b><br></b></li></ul>\n </td>\n</tr>\n<tr>\n <td style="width: 213px;"><strong>NO INCLUIDO [icon_tick state="off"] </strong></td>\n <td style="width: 574.233px;">\n  <b>Ingrese aquí lo que no va incluido en el paquete como una lista...</b>\n  <ul><li><b><br></b></li><li><b><br></b></li><li><b><br></b></li></ul>\n </td>\n</tr>\n</tbody>\n</table>\n', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='template_de',
            field=models.TextField(blank=True, null=True, verbose_name='Plantilla'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='template_en',
            field=models.TextField(blank=True, null=True, verbose_name='Plantilla'),
        ),
        migrations.AddField(
            model_name='optiontabdata',
            name='template_es',
            field=models.TextField(blank=True, null=True, verbose_name='Plantilla'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_de',
            field=models.TextField(blank=True, default='Sin comentario', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_en',
            field=models.TextField(blank=True, default='Sin comentario', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_es',
            field=models.TextField(blank=True, default='Sin comentario', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
