# Generated by Django 2.1.12 on 2019-09-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_auto_20190927_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
