# Generated by Django 2.1.12 on 2019-09-27 20:46

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_auto_20190927_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='special_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=19, verbose_name='Special price'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='sale_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=19, verbose_name='Precio rebajado'),
        ),
    ]
