# Generated by Django 2.1.12 on 2019-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_auto_20190930_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=40, null=True, verbose_name='Names')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Countries')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True, verbose_name='Whatsapp')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search',
                'ordering': ('email', 'country'),
            },
        ),
    ]
