# Generated by Django 2.1.12 on 2019-10-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_searchlanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=50, verbose_name='Firts Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dni', models.CharField(max_length=50, verbose_name='Identity number')),
                ('cellphone', models.CharField(max_length=50, verbose_name='Cellphone')),
                ('mail', models.EmailField(max_length=100, verbose_name='Email')),
                ('number_travel', models.CharField(max_length=2, verbose_name='Number of people travelling')),
                ('name_booking', models.CharField(blank=True, max_length=50, null=True, verbose_name='Booking')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('destination', models.ForeignKey(on_delete=False, to='destinations.Destination')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': "Booking's",
            },
        ),
        migrations.AlterModelOptions(
            name='searchlanding',
            options={'ordering': ('email', 'country'), 'verbose_name': 'Search Landing', 'verbose_name_plural': 'Search Landing'},
        ),
    ]
