# Generated by Django 2.1.12 on 2019-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_auto_20191002_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='process_status',
            field=models.BooleanField(default=False, help_text='Means if receive following or not.', verbose_name='status'),
        ),
    ]
