# Generated by Django 2.1.12 on 2019-10-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_booking_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seen_status',
            field=models.BooleanField(default=False, verbose_name='seen'),
        ),
    ]
