# Generated by Django 2.1.12 on 2019-10-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_booking_seen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='destinations.Categorie', verbose_name='Categorie'),
        ),
    ]
