# Generated by Django 2.1.12 on 2019-10-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_auto_20191003_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identity number'),
        ),
    ]
