# Generated by Django 2.1.12 on 2019-10-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_auto_20191003_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_travel',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Number of people travelling'),
        ),
    ]
