# Generated by Django 2.1.12 on 2019-10-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_auto_20191003_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_published',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_published'),
        ),
    ]
