# Generated by Django 2.1.12 on 2019-10-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0017_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='option_tab',
        ),
    ]
