# Generated by Django 2.1.12 on 2019-10-07 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0018_remove_itinerary_option_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination', verbose_name='Destination Rating')),
            ],
        ),
    ]
