# Generated by Django 2.1.12 on 2019-10-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0020_destinationmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmap',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='destinations.Destination', verbose_name='Map Destination'),
        ),
    ]
