# Generated by Django 2.1.12 on 2019-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0021_auto_20191007_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='number_of_reservations',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='tour_include',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='tour_not_include',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='transfer_from',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
