# Generated by Django 2.1.12 on 2019-10-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0022_auto_20191007_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
