# Generated by Django 2.1.12 on 2019-10-09 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0023_auto_20191007_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmap',
            name='description_map',
            field=models.CharField(default="NULL", max_length=50),
            preserve_default=False,
        ),
    ]
