# Generated by Django 2.1.12 on 2019-10-15 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0025_auto_20191014_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('booking', models.ForeignKey(on_delete=False, to='destinations.Booking', verbose_name='Booking')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
    ]
