# Generated by Django 2.1.12 on 2019-10-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0026_bookingstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstats',
            options={'verbose_name': 'Booking Stast', 'verbose_name_plural': 'Booking Stats'},
        ),
    ]
