# Generated by Django 2.1.12 on 2019-10-16 02:06

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0027_auto_20191015_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='special_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=19, null=True, verbose_name='Special price'),
        ),
    ]
