# Generated by Django 2.1.12 on 2019-10-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0029_auto_20191016_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='social_network',
            field=models.BooleanField(default=False, help_text='If you check this option it will show the social networks of the destination', verbose_name='Social Network'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination'),
        ),
    ]
