# Generated by Django 2.1.12 on 2019-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0032_destinationvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationvisitor',
            name='dma_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
