# Generated by Django 2.1.11 on 2020-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0034_auto_20191108_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='pinterest',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
