# Generated by Django 2.1.15 on 2020-05-29 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0035_auto_20200515_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=30, verbose_name='Company')),
                ('imagen_desktop', models.ImageField(help_text='Image to be displayed in desktop resolutions', upload_to='pic to desktop')),
                ('imagen_mobile', models.ImageField(help_text='Image to be displayed in mobile resolution', upload_to='pic to mobile')),
                ('position', models.IntegerField(choices=[(1, 'Up'), (2, 'Middle'), (2, 'Down')], default=1)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Start of advertising')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='End of advertising')),
                ('status', models.BooleanField(default=False, help_text='Indicate Advertising Status', verbose_name='Active')),
                ('url', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name_plural': 'Advertisements',
                'db_table': 'Advertising',
            },
        ),
    ]
