# Generated by Django 2.1.15 on 2020-05-29 02:18

from django.conf import settings
from django.db import migrations
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0036_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='imagen_desktop',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Image to be displayed in desktop resolutions', null=True, on_delete=False, related_name='Desktop', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='imagen_mobile',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Image to be displayed in mobile resolution', null=True, on_delete=False, related_name='mobile', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
