# Generated by Django 2.1.15 on 2020-05-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0037_auto_20200528_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name_plural': 'Ads'},
        ),
    ]
