# Generated by Django 2.1.11 on 2020-06-08 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0040_remove_messagedashboard_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedashboard',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dash_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
            preserve_default=False,
        ),
    ]
