# Generated by Django 2.1.11 on 2020-07-26 05:24

import apps.destinations.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0041_messagedashboard_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('description', models.TextField(blank=True, default='No comment', null=True, verbose_name='Description')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/video/', verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('user',), 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='destinationdetail',
            options={'verbose_name': 'Destination detail', 'verbose_name_plural': 'Destination details'},
        ),
        migrations.AlterModelOptions(
            name='generaldetail',
            options={'verbose_name': 'General detail', 'verbose_name_plural': 'General details'},
        ),
        migrations.AlterModelOptions(
            name='headersection',
            options={'verbose_name': 'Header section', 'verbose_name_plural': 'Header sections'},
        ),
        migrations.AlterModelOptions(
            name='inventariodetail',
            options={'verbose_name': 'Inventory detail', 'verbose_name_plural': 'Inventory details'},
        ),
        migrations.AlterModelOptions(
            name='optiontabdata',
            options={'ordering': ('name',), 'verbose_name': 'Tab option', 'verbose_name_plural': 'Tab options'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('sort', 'name'), 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='days',
            field=apps.destinations.fields.DaysCommaField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=[], max_length=14, null=True, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='destination_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='destinations.DestinationDetail', verbose_name='Destination detail'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='destinations.Categorie', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, default='\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class="table table-bordered tours-tabs__table" style="width: 100%px;">\n<tbody>\n<tr>\n<td style="width: 213px;"><strong>EXIT / RETURN</strong></td>\n<td style="width: 574.233px;"><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>EXIT TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>ARRIVAL TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style="width: 574.233px;"><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>TRANSFER FROM </strong></td>\n<td style="width: 574.233px;"><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_de',
            field=models.TextField(blank=True, default='\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class="table table-bordered tours-tabs__table" style="width: 100%px;">\n<tbody>\n<tr>\n<td style="width: 213px;"><strong>EXIT / RETURN</strong></td>\n<td style="width: 574.233px;"><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>EXIT TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>ARRIVAL TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style="width: 574.233px;"><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>TRANSFER FROM </strong></td>\n<td style="width: 574.233px;"><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_en',
            field=models.TextField(blank=True, default='\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class="table table-bordered tours-tabs__table" style="width: 100%px;">\n<tbody>\n<tr>\n<td style="width: 213px;"><strong>EXIT / RETURN</strong></td>\n<td style="width: 574.233px;"><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>EXIT TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>ARRIVAL TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style="width: 574.233px;"><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>TRANSFER FROM </strong></td>\n<td style="width: 574.233px;"><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_es',
            field=models.TextField(blank=True, default='\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class="table table-bordered tours-tabs__table" style="width: 100%px;">\n<tbody>\n<tr>\n<td style="width: 213px;"><strong>EXIT / RETURN</strong></td>\n<td style="width: 574.233px;"><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>EXIT TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>ARRIVAL TIME</strong></td>\n<td style="width: 574.233px;"><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style="width: 574.233px;"><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style="width: 213px;"><strong>TRANSFER FROM </strong></td>\n<td style="width: 574.233px;"><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_published',
            field=models.BooleanField(default=False, editable=False, verbose_name='is published?'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='destinationdetail',
            name='descargable',
            field=models.BooleanField(default=False, verbose_name='Downloadable'),
        ),
        migrations.AlterField(
            model_name='destinationdetail',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='class_imp',
            field=models.CharField(choices=[('estandar', 'Standard'), ('reduced', 'Reduced Rate'), ('zero', 'Zero Rate')], default='estandar', max_length=50, verbose_name='Tax type'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='date_on_sale_from',
            field=models.DateField(blank=True, null=True, verbose_name='Initial discount date'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='date_on_sale_to',
            field=models.DateField(blank=True, null=True, verbose_name='Final discount date'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='destination_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general', to='destinations.DestinationDetail', verbose_name='Destination detail'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='regular_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=19, verbose_name='Normal price'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='sale_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=19, verbose_name='Reduced price'),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='status_imp',
            field=models.CharField(choices=[('imponible', 'Impossible'), ('envio', 'Shipping only'), ('ninguno', 'None')], default='imponible', max_length=50, verbose_name='Tax status'),
        ),
        migrations.AlterField(
            model_name='headersection',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='headersection',
            name='display_mode',
            field=models.CharField(choices=[('hide', 'Default'), ('banner', 'Image'), ('slider', 'Slider'), ('from_list', 'From list')], default='hide', max_length=15, verbose_name='Display mode'),
        ),
        migrations.AlterField(
            model_name='headersection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='header/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='headersection',
            name='image_repeat',
            field=models.CharField(blank=True, choices=[('repeat', 'Repeat'), ('no-repeat', 'No repeat'), ('repeat-x', 'Repeat horizontally'), ('repeat-y', 'Repeat vertically')], max_length=150, null=True, verbose_name='Image repeat'),
        ),
        migrations.AlterField(
            model_name='inventariodetail',
            name='destination_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='destinations.DestinationDetail', verbose_name='Destination detail'),
        ),
        migrations.AlterField(
            model_name='inventariodetail',
            name='manager',
            field=models.BooleanField(default=False, help_text='Activate inventory management for each product', verbose_name='Inventory management?'),
        ),
        migrations.AlterField(
            model_name='inventariodetail',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inventory quantity'),
        ),
        migrations.AlterField(
            model_name='inventariodetail',
            name='reserva',
            field=models.CharField(choices=[('no', 'Do not allow'), ('notify', 'Allow, but the customer will be warned'), ('yes', 'Allow')], default='no', max_length=50, verbose_name='Allow reservations?'),
        ),
        migrations.AlterField(
            model_name='inventariodetail',
            name='sold_individually',
            field=models.BooleanField(default=False, help_text='Activate this to allow only one of these items to be purchased in each order', verbose_name='Sold individually'),
        ),
        migrations.AlterField(
            model_name='inventariodetail',
            name='umb_exist',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Low stock threshold'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='template',
            field=models.TextField(blank=True, null=True, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='template_de',
            field=models.TextField(blank=True, null=True, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='template_en',
            field=models.TextField(blank=True, null=True, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='optiontabdata',
            name='template_es',
            field=models.TextField(blank=True, null=True, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default='No comment', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_de',
            field=models.TextField(blank=True, default='No comment', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_en',
            field=models.TextField(blank=True, default='No comment', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_es',
            field=models.TextField(blank=True, default='No comment', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tourdata',
            name='badge',
            field=models.CharField(blank=True, choices=[('1', 'Last minute'), ('2', 'Deal of the Month'), ('3', 'FamTrip'), ('4', 'Congresses'), ('5', 'Events'), ('6', 'Hotel'), ('7', 'Mobility'), ('8', 'Leisure +')], max_length=150, null=True, verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='tourdata',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='video',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='destinations.Destination', verbose_name='Destination'),
        ),
    ]
