# Generated by Django 2.1.11 on 2020-07-07 13:43

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0042_auto_20200704_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Advertising', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='destinationmap',
            options={'verbose_name': 'Destination Map', 'verbose_name_plural': 'Destination Maps'},
        ),
        migrations.AlterModelOptions(
            name='destinationrating',
            options={'verbose_name': 'Destination Rating', 'verbose_name_plural': 'Destinations Rating'},
        ),
        migrations.AlterModelOptions(
            name='destinationvisitor',
            options={'verbose_name': 'Destination Visitor', 'verbose_name_plural': 'Destination Visitors'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='messagedashboard',
            options={'verbose_name': 'Message Dashboard', 'verbose_name_plural': 'Messages Dashboard'},
        ),
        migrations.AlterField(
            model_name='advertising',
            name='imagen_desktop',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Image to be displayed in desktop resolutions', null=True, on_delete=False, related_name='desktop', to=settings.FILER_IMAGE_MODEL, verbose_name='Desktop Image'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='imagen_mobile',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Image to be displayed in mobile resolution', null=True, on_delete=False, related_name='mobile', to=settings.FILER_IMAGE_MODEL, verbose_name='Mobile Image'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='position',
            field=models.IntegerField(choices=[(1, 'Up'), (2, 'Middle'), (2, 'Down')], default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=False, to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Departure Time'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, default="\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class='table table-bordered tours-tabs__table'\n       style='width: 100%px;'>\n<tbody>\n<tr>\n<td style='width: 213px;'><strong>EXIT / RETURN</strong></td>\n<td style='width: 574.233px;'><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>EXIT TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>ARRIVAL TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style='width: 574.233px;'><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>TRANSFER FROM </strong></td>\n<td style='width: 574.233px;'><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_de',
            field=models.TextField(blank=True, default="\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class='table table-bordered tours-tabs__table'\n       style='width: 100%px;'>\n<tbody>\n<tr>\n<td style='width: 213px;'><strong>EXIT / RETURN</strong></td>\n<td style='width: 574.233px;'><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>EXIT TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>ARRIVAL TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style='width: 574.233px;'><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>TRANSFER FROM </strong></td>\n<td style='width: 574.233px;'><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_en',
            field=models.TextField(blank=True, default="\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class='table table-bordered tours-tabs__table'\n       style='width: 100%px;'>\n<tbody>\n<tr>\n<td style='width: 213px;'><strong>EXIT / RETURN</strong></td>\n<td style='width: 574.233px;'><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>EXIT TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>ARRIVAL TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style='width: 574.233px;'><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>TRANSFER FROM </strong></td>\n<td style='width: 574.233px;'><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_es',
            field=models.TextField(blank=True, default="\n<strong>Who we are</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<strong>Mission</strong><br><br>\n\n<p><b>Please enter your text here...</b></p><br><br>\n\n<table class='table table-bordered tours-tabs__table'\n       style='width: 100%px;'>\n<tbody>\n<tr>\n<td style='width: 213px;'><strong>EXIT / RETURN</strong></td>\n<td style='width: 574.233px;'><b>Enter the exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>EXIT TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of exit here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>ARRIVAL TIME</strong></td>\n<td style='width: 574.233px;'><b>Enter the time of arrival here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>NR. OF TOUR FOR RESERVATIONS</strong></td>\n<td style='width: 574.233px;'><b>Enter the tour number here...</b></td>\n</tr>\n<tr>\n<td style='width: 213px;'><strong>TRANSFER FROM </strong></td>\n<td style='width: 574.233px;'><strong><b>Enter the transfer here...</b></strong></td>\n</tr>\n</tbody>\n</table>\n", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='number_of_reservations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Reservations'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tour_include',
            field=models.TextField(blank=True, verbose_name='Tour include'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tour_not_include',
            field=models.TextField(blank=True, verbose_name='Tour not include'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='transfer_from',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Transfer from'),
        ),
        migrations.AlterField(
            model_name='destinationmap',
            name='description_map',
            field=models.CharField(max_length=50, verbose_name='Description Map'),
        ),
        migrations.AlterField(
            model_name='destinationmap',
            name='map_destinie',
            field=django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326, verbose_name='Destinie Map'),
        ),
        migrations.AlterField(
            model_name='destinationvisitor',
            name='country_code',
            field=models.CharField(max_length=5, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='destinationvisitor',
            name='country_name',
            field=models.CharField(max_length=100, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='destinationvisitor',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date/time'),
        ),
        migrations.AlterField(
            model_name='destinationvisitor',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='destinationvisitor',
            name='dma_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dma Code'),
        ),
        migrations.AlterField(
            model_name='destinationvisitor',
            name='ip_address',
            field=models.CharField(max_length=100, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='pinterest',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Website'),
        ),
    ]
