# Generated by Django 2.1.11 on 2020-07-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0043_video_thumbnail_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Booking Choice',
                'verbose_name_plural': 'Booking Choices',
            },
        ),
        migrations.CreateModel(
            name='BookingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Booking Question',
                'verbose_name_plural': 'Booking Questions',
            },
        ),
        migrations.AddField(
            model_name='bookingchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.BookingQuestion'),
        ),
    ]
