# Generated by Django 2.1.11 on 2020-07-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0044_auto_20200729_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingchoice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Choice text'),
        ),
        migrations.AlterField(
            model_name='bookingchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.BookingQuestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='bookingchoice',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
        migrations.AlterField(
            model_name='bookingquestion',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question text'),
        ),
    ]
