# Generated by Django 2.1.11 on 2020-08-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0045_auto_20200730_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Destination has Air conditioning?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_bar',
            field=models.BooleanField(default=False, verbose_name='Destination has Bar?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_breakfast_incluided',
            field=models.BooleanField(default=False, verbose_name='Destination has Breakfast included?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_business_services',
            field=models.BooleanField(default=False, verbose_name='Destination has Business Services?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_front_desk',
            field=models.BooleanField(default=False, verbose_name='Destination has 25/7 Front Desk?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_gym',
            field=models.BooleanField(default=False, verbose_name='Destination has Gym?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_hob_tub',
            field=models.BooleanField(default=False, verbose_name='Destination has Hob Tub?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_housekeeping',
            field=models.BooleanField(default=False, verbose_name='Destination has Housekeeping service?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_laundry',
            field=models.BooleanField(default=False, verbose_name='Destination has laundry service?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_restaurant',
            field=models.BooleanField(default=False, verbose_name='Destination has restaurant?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_room_service',
            field=models.BooleanField(default=False, verbose_name='Destination has Room service?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Destination has Wifi?'),
        ),
    ]
