# Generated by Django 2.1.11 on 2020-08-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0046_auto_20200805_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='has_business_services',
            field=models.BooleanField(default=False, verbose_name='Destination has Business services?'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='has_laundry',
            field=models.BooleanField(default=False, verbose_name='Destination has Laundry service?'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='has_restaurant',
            field=models.BooleanField(default=False, verbose_name='Destination has Restaurant?'),
        ),
    ]
