# Generated by Django 2.1.11 on 2020-08-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0047_auto_20200805_0104'),
        ('destinations', '0046_auto_20200825_0742'),
    ]

    operations = [
    ]
