# Generated by Django 2.1.11 on 2020-08-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0043_auto_20200707_0943'),
        ('destinations', '0047_auto_20200805_0104'),
    ]

    operations = [
    ]
