# Generated by Django 2.1.11 on 2020-08-23 00:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0048_merge_20200821_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmap',
            name='map_destinie',
            field=django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326, verbose_name='Destination Map'),
        ),
    ]
