# Generated by Django 2.1.11 on 2020-08-26 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0011_auto_20190418_0137'),
        ('destinations', '0048_merge_20200825_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('status', models.BooleanField(default=True, help_text='Indicate Status', verbose_name='Active')),
                ('image', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='filer.File')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='country',
            field=models.CharField(choices=[('KP', "Korea (the Democratic People's Republic of)"), ('PE', 'Peru'), ('BD', 'Bangladesh'), ('TD', 'Chad'), ('ID', 'Indonesia'), ('KZ', 'Kazakhstan'), ('VC', 'Saint Vincent and the Grenadines'), ('NP', 'Nepal'), ('BJ', 'Benin'), ('NO', 'Norway'), ('AL', 'Albania'), ('UM', 'United States Minor Outlying Islands'), ('VA', 'Holy See'), ('FM', 'Micronesia (Federated States of)'), ('PH', 'Philippines'), ('TZ', 'Tanzania, the United Republic of'), ('CV', 'Cabo Verde'), ('RE', 'Réunion'), ('PS', 'Palestine, State of'), ('PG', 'Papua New Guinea'), ('MN', 'Mongolia'), ('BW', 'Botswana'), ('WS', 'Samoa'), ('EE', 'Estonia'), ('GI', 'Gibraltar'), ('GG', 'Guernsey'), ('HT', 'Haiti'), ('GP', 'Guadeloupe'), ('BA', 'Bosnia and Herzegovina'), ('SD', 'Sudan'), ('SJ', 'Svalbard and Jan Mayen'), ('BO', 'Bolivia (Plurinational State of)'), ('MM', 'Myanmar'), ('FO', 'Faroe Islands'), ('KN', 'Saint Kitts and Nevis'), ('CY', 'Cyprus'), ('AF', 'Afghanistan'), ('ER', 'Eritrea'), ('DK', 'Denmark'), ('GT', 'Guatemala'), ('TN', 'Tunisia'), ('IQ', 'Iraq'), ('BZ', 'Belize'), ('CD', 'Congo (the Democratic Republic of the)'), ('VU', 'Vanuatu'), ('CN', 'China'), ('GL', 'Greenland'), ('TR', 'Turkey'), ('ML', 'Mali'), ('KM', 'Comoros'), ('GF', 'French Guiana'), ('GH', 'Ghana'), ('UZ', 'Uzbekistan'), ('LB', 'Lebanon'), ('SX', 'Sint Maarten (Dutch part)'), ('CC', 'Cocos (Keeling) Islands'), ('GW', 'Guinea-Bissau'), ('RS', 'Serbia'), ('PM', 'Saint Pierre and Miquelon'), ('SI', 'Slovenia'), ('MO', 'Macao'), ('MS', 'Montserrat'), ('CH', 'Switzerland'), ('VG', 'Virgin Islands (British)'), ('LR', 'Liberia'), ('KH', 'Cambodia'), ('JO', 'Jordan'), ('GD', 'Grenada'), ('PA', 'Panama'), ('PW', 'Palau'), ('CX', 'Christmas Island'), ('SR', 'Suriname'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('LI', 'Liechtenstein'), ('MZ', 'Mozambique'), ('VI', 'Virgin Islands (U.S.)'), ('IN', 'India'), ('IM', 'Isle of Man'), ('KI', 'Kiribati'), ('BT', 'Bhutan'), ('HN', 'Honduras'), ('CR', 'Costa Rica'), ('NG', 'Nigeria'), ('BI', 'Burundi'), ('NE', 'Niger'), ('MA', 'Morocco'), ('ZM', 'Zambia'), ('AI', 'Anguilla'), ('LY', 'Libya'), ('TK', 'Tokelau'), ('NC', 'New Caledonia'), ('IO', 'British Indian Ocean Territory'), ('GE', 'Georgia'), ('MU', 'Mauritius'), ('BG', 'Bulgaria'), ('TH', 'Thailand'), ('GB', 'United Kingdom of Great Britain and Northern Ireland'), ('LS', 'Lesotho'), ('FK', 'Falkland Islands (Malvinas)'), ('HK', 'Hong Kong'), ('SL', 'Sierra Leone'), ('MR', 'Mauritania'), ('IS', 'Iceland'), ('MG', 'Madagascar'), ('SK', 'Slovakia'), ('AZ', 'Azerbaijan'), ('EC', 'Ecuador'), ('SM', 'San Marino'), ('AG', 'Antigua and Barbuda'), ('CI', "Côte d'Ivoire"), ('FJ', 'Fiji'), ('SG', 'Singapore'), ('NA', 'Namibia'), ('BH', 'Bahrain'), ('MV', 'Maldives'), ('PN', 'Pitcairn'), ('AX', 'Åland Islands'), ('IE', 'Ireland'), ('MP', 'Northern Mariana Islands'), ('TC', 'Turks and Caicos Islands'), ('SO', 'Somalia'), ('GY', 'Guyana'), ('SA', 'Saudi Arabia'), ('AU', 'Australia'), ('AE', 'United Arab Emirates'), ('LV', 'Latvia'), ('BV', 'Bouvet Island'), ('FR', 'France'), ('SE', 'Sweden'), ('SN', 'Senegal'), ('HU', 'Hungary'), ('DO', 'Dominican Republic'), ('ZA', 'South Africa'), ('TW', 'Taiwan (Province of China)'), ('TV', 'Tuvalu'), ('MC', 'Monaco'), ('MD', 'Moldova (the Republic of)'), ('PF', 'French Polynesia'), ('ME', 'Montenegro'), ('ES', 'Spain'), ('MH', 'Marshall Islands'), ('HR', 'Croatia'), ('PY', 'Paraguay'), ('GS', 'South Georgia and the South Sandwich Islands'), ('IL', 'Israel'), ('YT', 'Mayotte'), ('TG', 'Togo'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('RW', 'Rwanda'), ('GM', 'Gambia'), ('GR', 'Greece'), ('CZ', 'Czechia'), ('LC', 'Saint Lucia'), ('AS', 'American Samoa'), ('AM', 'Armenia'), ('MQ', 'Martinique'), ('VN', 'Viet Nam'), ('KY', 'Cayman Islands'), ('MK', 'North Macedonia'), ('IR', 'Iran (Islamic Republic of)'), ('OM', 'Oman'), ('ST', 'Sao Tome and Principe'), ('TJ', 'Tajikistan'), ('UA', 'Ukraine'), ('UG', 'Uganda'), ('CU', 'Cuba'), ('UY', 'Uruguay'), ('ET', 'Ethiopia'), ('CF', 'Central African Republic'), ('AD', 'Andorra'), ('KW', 'Kuwait'), ('BB', 'Barbados'), ('PL', 'Poland'), ('CK', 'Cook Islands'), ('DJ', 'Djibouti'), ('NZ', 'New Zealand'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('BF', 'Burkina Faso'), ('RU', 'Russian Federation'), ('CM', 'Cameroon'), ('LK', 'Sri Lanka'), ('VE', 'Venezuela (Bolivarian Republic of)'), ('NU', 'Niue'), ('AQ', 'Antarctica'), ('KG', 'Kyrgyzstan'), ('HM', 'Heard Island and McDonald Islands'), ('MX', 'Mexico'), ('EG', 'Egypt'), ('SY', 'Syrian Arab Republic'), ('QA', 'Qatar'), ('NI', 'Nicaragua'), ('CA', 'Canada'), ('SB', 'Solomon Islands'), ('AT', 'Austria'), ('BM', 'Bermuda'), ('SV', 'El Salvador'), ('MT', 'Malta'), ('KE', 'Kenya'), ('WF', 'Wallis and Futuna'), ('JE', 'Jersey'), ('PR', 'Puerto Rico'), ('MF', 'Saint Martin (French part)'), ('TT', 'Trinidad and Tobago'), ('SC', 'Seychelles'), ('SZ', 'Eswatini'), ('CL', 'Chile'), ('IT', 'Italy'), ('CW', 'Curaçao'), ('FI', 'Finland'), ('TL', 'Timor-Leste'), ('LA', "Lao People's Democratic Republic"), ('DZ', 'Algeria'), ('LU', 'Luxembourg'), ('AW', 'Aruba'), ('BR', 'Brazil'), ('TF', 'French Southern Territories'), ('KR', 'Korea (the Republic of)'), ('SS', 'South Sudan'), ('CG', 'Congo'), ('GA', 'Gabon'), ('TM', 'Turkmenistan'), ('YE', 'Yemen'), ('BL', 'Saint Barthélemy'), ('MY', 'Malaysia'), ('RO', 'Romania'), ('BE', 'Belgium'), ('MW', 'Malawi'), ('BY', 'Belarus'), ('AR', 'Argentina'), ('GN', 'Guinea'), ('EH', 'Western Sahara'), ('BN', 'Brunei Darussalam'), ('TO', 'Tonga'), ('BS', 'Bahamas'), ('JP', 'Japan'), ('AO', 'Angola'), ('LT', 'Lithuania'), ('DM', 'Dominica'), ('PK', 'Pakistan'), ('PT', 'Portugal'), ('CO', 'Colombia'), ('GU', 'Guam'), ('US', 'United States of America'), ('ZW', 'Zimbabwe'), ('GQ', 'Equatorial Guinea'), ('NR', 'Nauru'), ('NF', 'Norfolk Island'), ('JM', 'Jamaica')], max_length=3, verbose_name='Countries'),
        ),
    ]
