# Generated by Django 2.1.11 on 2020-08-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0049_auto_20200822_2025'),
        ('destinations', '0045_auto_20200810_2353'),
    ]

    operations = [
    ]
