# Generated by Django 2.1.11 on 2020-08-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0050_auto_20200825_2327'),
        ('destinations', '0048_merge_20200825_0803'),
    ]

    operations = [
    ]
