# Generated by Django 2.1.11 on 2020-08-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0052_auto_20200829_0958'),
        ('destinations', '0051_merge_20200829_0958'),
    ]

    operations = [
    ]
