# Generated by Django 2.1.11 on 2020-08-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0053_auto_20200831_1303'),
        ('destinations', '0052_auto_20200830_1522'),
    ]

    operations = [
    ]
