# Generated by Django 2.1.11 on 2020-09-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0053_merge_20200829_1007'),
        ('destinations', '0054_merge_20200831_1905'),
    ]

    operations = [
    ]
