# Generated by Django 2.1.11 on 2020-09-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0057_auto_20200902_2238'),
        ('destinations', '0056_auto_20200902_2013'),
    ]

    operations = [
    ]
