# Generated by Django 2.1.15 on 2020-01-03 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0034_auto_20191108_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, help_text='Would you recommend this trip again?', null=True)),
                ('recommendation2', models.TextField(blank=True, help_text='Do you think we should get better?', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=None, related_name='destino', to='destinations.Destination')),
                ('user_recommendation', models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
            },
        ),
    ]
