# Generated by Django 2.1.15 on 2020-01-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='updated',
        ),
    ]
