# Generated by Django 2.1.15 on 2020-01-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
