# Generated by Django 2.1.14 on 2020-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(max_length=40),
        ),
    ]
