# Generated by Django 2.1.11 on 2020-07-07 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200219_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='destino',
            field=models.ForeignKey(on_delete=None, related_name='destino', to='destinations.Destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Would you recommend this trip again?', null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation2',
            field=models.TextField(blank=True, help_text='Do you think we should get better?', null=True, verbose_name='Recommendation Others'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user_recommendation',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendation', to=settings.AUTH_USER_MODEL, verbose_name='User Recommendation'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referredBy', to=settings.AUTH_USER_MODEL, verbose_name='Referred By'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
