# Generated by Django 2.2 on 2019-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_coupon_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.SlugField(unique=True, verbose_name='code'),
        ),
    ]
