# Generated by Django 2.1.11 on 2020-07-04 10:57

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191021_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=8, null=True, verbose_name='Price'),
        ),
    ]
