# Generated by Django 2.1.11 on 2020-08-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200704_0657'),
        ('payments', '0004_auto_20200707_0943'),
    ]

    operations = [
    ]
