# Generated by Django 2.1.12 on 2019-09-27 16:00

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190829_0907'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customeruser',
            name='business_position_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo en la empresa'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='business_position_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo en la empresa'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='business_position_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo en la empresa'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='comment_de',
            field=models.TextField(blank=True, null=True, verbose_name='¿Tienen algo que decirnos?'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='¿Tienen algo que decirnos?'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='comment_es',
            field=models.TextField(blank=True, null=True, verbose_name='¿Tienen algo que decirnos?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('de', 'de'), ('es', 'es')], default='en', max_length=2, verbose_name='Idiomas en los que le interesa enviar o recibir información'),
        ),
    ]
