# Generated by Django 2.1.12 on 2019-09-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190927_1517'),
        ('accounts', '0005_auto_20190927_1520'),
    ]

    operations = [
    ]
