# Generated by Django 2.1.12 on 2019-11-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20191108_1614'),
        ('accounts', '0042_auto_20191022_2214'),
    ]

    operations = [
    ]
