# Generated by Django 2.1.12 on 2019-12-15 23:27

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20191215_1538'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_answer',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
