# Generated by Django 2.1.12 on 2019-12-16 02:54

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20191215_2146'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.IntegerField(blank=True, null=True, verbose_name='Like'),
        ),
    ]
