# Generated by Django 2.1.12 on 2019-12-17 00:26

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20191216_1239'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parent'),
        ),
    ]
