# Generated by Django 2.1.15 on 2020-01-10 15:01

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_auto_20200107_2337'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customeruser',
            name='ref_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code Referral'),
        ),
    ]
