# Generated by Django 2.1.14 on 2020-02-04 15:47

import apps.accounts.models
import apps.utils.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_auto_20200204_0957'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='ref_code',
            field=models.CharField(default=apps.utils.views.get_referal_code, max_length=20, verbose_name='Code Referral'),
        ),
    ]
