# Generated by Django 2.1.11 on 2020-06-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_auto_20200606_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='slug',
            field=models.SlugField(default=1, unique=True)
            )
    ]
