# Generated by Django 2.1.11 on 2020-07-04 10:57

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_auto_20200606_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='business_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Commercial address'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='business_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position in the company'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='business_position_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position in the company'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='business_position_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position in the company'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='business_position_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position in the company'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Do you have something to tell us?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='comment_de',
            field=models.TextField(blank=True, null=True, verbose_name='Do you have something to tell us?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Do you have something to tell us?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='comment_es',
            field=models.TextField(blank=True, null=True, verbose_name='Do you have something to tell us?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='degree',
            field=models.CharField(blank=True, choices=[('sra', 'Mrs.'), ('sr', 'Mr.'), ('divers', 'Divers'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('lic', 'Lic.'), ('agrupacion', 'Grouping'), ('prof-dr', 'Prof. Dr.')], max_length=20, null=True, verbose_name='Title (Contact person)'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('de', 'de'), ('es', 'es')], default='en', max_length=2, verbose_name='Languages in which you are interested in sending or receiving information'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile number or WhatsApp'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Leave us a phone number where we can contact you'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City / State / Parish'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='Leave us your web address'),
        ),
    ]
