# Generated by Django 2.1.11 on 2020-07-07 13:43

import apps.accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_auto_20200704_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='lastvisitip',
            options={'verbose_name': 'Last Visit IP', 'verbose_name_plural': 'Lasts Visits IP'},
        ),
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Body Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='height_field',
            field=models.IntegerField(default=0, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=None, related_name='comments', to='destinations.Destination', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_answer',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_to', to=settings.AUTH_USER_MODEL, verbose_name='User Answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_to', to=settings.AUTH_USER_MODEL, verbose_name='User Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='width_field',
            field=models.IntegerField(default=0, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL, verbose_name='User that creates the relationship'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL, verbose_name='User being followed'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_community',
            field=models.BooleanField(default=True, verbose_name='is community?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is superuser?'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='pinterest',
            field=models.URLField(blank=True, null=True, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='SLUG'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='subscription_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Subscription ID'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='lastvisitip',
            name='last_ip_login',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Last Login IP'),
        ),
        migrations.AlterField(
            model_name='lastvisitip',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='lastvisitip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
