# Generated by Django 2.1.11 on 2020-08-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_auto_20200708_2111'),
        ('accounts', '0088_auto_20200707_0943'),
    ]

    operations = [
    ]
