# Generated by Django 2.1.11 on 2019-08-29 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='landing_page.Feature', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.Feature', verbose_name='feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.Plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'plan-feature',
                'verbose_name_plural': 'plan-features',
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Price type',
                'verbose_name_plural': 'Price types',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.CharField(default='fa-', help_text='Icons use of Font Awesome 4.7.0, info: https://fontawesome.com/v4.7.0/icons/', max_length=20, verbose_name='icon')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=150, verbose_name='description')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='landing/slider', verbose_name='image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('type', models.CharField(choices=[('h', 'Header'), ('c', 'Company')], default='h', max_length=5, verbose_name='type')),
                ('site', models.URLField(blank=True, null=True, verbose_name='site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.CharField(default='fa-', help_text='Icons use of Font Awesome 4.7.0, info: https://fontawesome.com/v4.7.0/icons/', max_length=20, verbose_name='icon')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('counter', models.BooleanField(default=True, verbose_name='counter')),
            ],
            options={
                'verbose_name': 'statistic',
                'verbose_name_plural': 'statistics',
                'ordering': ('order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('comment', models.TextField(verbose_name='comment')),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='landing/testimonies/', verbose_name='photo')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='price',
            name='type',
            field=models.ForeignKey(on_delete=None, to='landing_page.PriceType'),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(related_name='features', through='landing_page.PlanFeature', to='landing_page.Feature', verbose_name='features'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.ManyToManyField(blank=True, to='landing_page.Price', verbose_name='Prices'),
        ),
        migrations.AddField(
            model_name='feature',
            name='validated_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing_page.Plan', verbose_name='validated to plan'),
        ),
    ]
