# Generated by Django 2.1.12 on 2019-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name_de',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_es',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_de',
            field=models.TextField(max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_de',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_es',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='value_de',
            field=models.CharField(max_length=50, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='value_es',
            field=models.CharField(max_length=50, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='comment_de',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='comment_es',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='place_de',
            field=models.CharField(max_length=50, null=True, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='place_en',
            field=models.CharField(max_length=50, null=True, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='place_es',
            field=models.CharField(max_length=50, null=True, verbose_name='place'),
        ),
    ]
