# Generated by Django 2.1.12 on 2019-09-15 11:18

from django.conf import settings
from django.db import migrations, models
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('landing_page', '0002_auto_20190902_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('editor', models.CharField(max_length=50, verbose_name='Editor')),
                ('estatus', models.BooleanField(default=True, verbose_name='is active?')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('files', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=False, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Megazine',
                'verbose_name_plural': 'Megazines',
                'ordering': ('name', 'order'),
            },
        ),
    ]
