# Generated by Django 2.1.12 on 2019-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20190915_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='kliche',
            field=models.BooleanField(default=False, verbose_name='outstanding'),
        ),
    ]
