# Generated by Django 2.1.12 on 2019-09-15 19:54

from django.conf import settings
from django.db import migrations
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('landing_page', '0005_magazine_kliche'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='magazine',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=False, related_name='magazine_file', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='files',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=False, related_name='file_magazine', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
