# Generated by Django 2.1.12 on 2019-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_auto_20190915_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
    ]
