# Generated by Django 2.1.12 on 2019-10-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_deletereg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Address IP')),
                ('cookie', models.BooleanField(default=True, verbose_name='cookies')),
                ('ganality', models.BooleanField(default=True, verbose_name='Google Analitys')),
                ('facebook', models.BooleanField(default=True, verbose_name='Facebook Pixel')),
                ('twitter', models.BooleanField(default=True, verbose_name='Twitter')),
                ('pinteres', models.BooleanField(default=True, verbose_name='Pinteres')),
            ],
            options={
                'verbose_name': 'Privacity Setting',
                'verbose_name_plural': 'Privacity Settings',
            },
        ),
    ]
