# Generated by Django 2.1.12 on 2019-10-23 02:14

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_privacysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=19, verbose_name='Value'),
        ),
    ]
